/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bk7Qhvjsffb
 */
import { Input } from "@/components/ui/input"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { RadioGroupItem, RadioGroup } from "@/components/ui/radio-group"
import { Label } from "@/components/ui/label"
import { Badge } from "@/components/ui/badge"

export function ServiceCard() {
  return (
    <div className="max-w-md mx-auto p-6 bg-white shadow-lg rounded-lg">
      <h2 className="text-2xl font-semibold mb-6">Tell us about your cleaning needs</h2>
      <div className="mb-4">
        <label className="block text-sm font-medium mb-1" htmlFor="apartment-size">
          Apartment Size
        </label>
        <div className="flex items-center">
          <Input className="w-full" id="apartment-size" placeholder="400" type="number" />
          <span className="ml-2 text-sm">m²</span>
        </div>
      </div>
      <div className="mb-6">
        <label className="block text-sm font-medium mb-1" htmlFor="cleaning-duration">
          Cleaning Duration
        </label>
        <Select>
          <SelectTrigger id="cleaning-duration">
            <SelectValue placeholder="8 hours (recommendation)" />
          </SelectTrigger>
          <SelectContent position="popper">
            <SelectItem value="8">8 hours (recommendation)</SelectItem>
            <SelectItem value="4">4 hours</SelectItem>
            <SelectItem value="12">12 hours</SelectItem>
          </SelectContent>
        </Select>
      </div>
      <div className="mb-6">
        <h3 className="text-sm font-medium mb-1">How often should we clean?</h3>
        <p className="text-sm mb-4">With Freska you will get a regular cleaner!</p>
        <div className="space-y-4">
          <RadioGroup defaultValue="every-week">
            <div className="flex justify-between items-center p-4 bg-gray-100 rounded-lg border-2 border-black">
              <RadioGroupItem id="every-week" value="every-week" />
              <Label className="text-sm font-medium" htmlFor="every-week">
                Every week
              </Label>
              <span className="text-lg font-semibold">324 kr/h</span>
              <span className="text-sm">648 kr/h without RUT deduction</span>
            </div>
            <div className="flex justify-between items-center p-4 bg-gray-100 rounded-lg">
              <RadioGroupItem id="every-second-week" value="every-second-week" />
              <Label className="text-sm font-medium" htmlFor="every-second-week">
                Every second week
              </Label>
              <Badge variant="secondary">Most popular</Badge>
              <span className="text-lg font-semibold">334 kr/h</span>
              <span className="text-sm">668 kr/h without RUT deduction</span>
            </div>
            <div className="flex justify-between items-center p-4 bg-gray-100 rounded-lg">
              <RadioGroupItem id="every-fourth-week" value="every-fourth-week" />
              <Label className="text-sm font-medium" htmlFor="every-fourth-week">
                Every fourth week
              </Label>
              <span className="text-lg font-semibold">349 kr/h</span>
              <span className="text-sm">698 kr/h without RUT deduction</span>
            </div>
            <div className="flex items-center space-x-2">
              <RadioGroupItem id="one-time" value="one-time" />
              <Label className="text-sm font-medium" htmlFor="one-time">
                One time only (429 kr/h)
              </Label>
              <span className="text-sm">858 kr/h without RUT deduction</span>
            </div>
          </RadioGroup>
        </div>
      </div>
      <div className="mb-6">
        <h3 className="text-sm font-medium mb-1">Eco-friendly cleaning supplies</h3>
        <div className="flex items-start space-x-2">
          <InfoIcon className="mt-1 h-6 w-6 text-blue-600" />
          <p className="text-sm">
            Freska's eco-friendly and allergy-friendly cleaning supplies are included in your order! Do you have a
            vacuum cleaner, bucket & mop? We use them.
          </p>
        </div>
      </div>
    </div>
  )
}


function InfoIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M12 16v-4" />
      <path d="M12 8h.01" />
    </svg>
  )
}
