import './globals.css'
import type { Metadata } from 'next'
import { Locale, i18n } from '@/i18n.config'
import Header from './components/header'
import { Toaster } from "@/components/ui/toaster"
import { Poppins, Sora } from 'next/font/google'

import Footer from '@/components/footer/Footer'
import TanstackProvider from '@/providers/TanstackProvider'

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export async function generateStaticParams() {
  return i18n.locales.map(locale => ({ lang: locale }))
}

export default function RootLayout({
  children,
  params
}: {
  children: React.ReactNode
  params: { lang: Locale }
}) {
  return (
    <html lang={params.lang}>
      <body className={`${poppins.variable}`}>
        <TanstackProvider>
          <Header lang={params.lang} />
          <main>{children}</main>
          <Footer lang={params.lang} />
          <Toaster />
        </TanstackProvider>
      </body>
    </html>
  )
}
